# Generated by Django 4.1.9 on 2023-06-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_company_name_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
