# Generated by Django 4.1.9 on 2023-07-06 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('contacts', '0010_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='representative_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
