# Generated by Django 4.1.9 on 2023-07-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_person_representative_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_contact',
            field=models.BooleanField(default=False),
        ),
    ]
