# Generated by Django 4.1.9 on 2023-07-24 13:20

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_person_is_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contacts_story',
            field=wagtail.fields.RichTextField(blank=True, help_text='Description of contacts'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='short_story',
            field=wagtail.fields.RichTextField(blank=True, help_text='Short description of contacts'),
        ),
    ]
