# Generated by Django 4.1.9 on 2023-07-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_projectrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrole',
            name='persons',
            field=models.ManyToManyField(blank=True, to='contacts.person'),
        ),
    ]
