version: '3.7'

services:
  web:
    build: .
    command: sh entrypoint.prod.sh
    volumes:
      - .:/usr/src/app/
    ports:
      - 8010:8000
    env_file:
      - .env.dev
    depends_on:
      - dbd

  dbd:
    image: postgres
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file:
      - .env.db


