version: '3.7'

services:
  b2bweb:
    build: .
    command: sh entrypoint.prod.sh
    volumes:
      - .:/usr/src/app/
    expose:
      - 8000
    env_file:
      - .env.dev
<<<<<<< Updated upstream
=======
    depends_on:
      - dbd

  dbd:
    image: postgres
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file:
      - .env.db

  nginx:
    image: library/nginx:latest
    container_name: docker-b2b-nginx
    ports:
      - "8082:8090"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media
    depends_on:
      - dbd
      - b2bweb
>>>>>>> Stashed changes
