# Generated by Django 4.1.1 on 2022-09-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'B2B main page'},
        ),
    ]
