# Generated by Django 4.1.9 on 2023-06-19 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
