# Generated by Django 4.1.1 on 2022-09-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_filefolder_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectFile',
        ),
    ]
