# Generated by Django 4.1.1 on 2022-09-17 21:18

import core.tools
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0076_modellogentry_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_delete_projectfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('article_date', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('featured_image', models.FileField(blank=True, null=True, upload_to=core.tools.file_path)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('news_project', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
