# Generated by Django 4.1.1 on 2022-09-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_newsarticle_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfolder',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
