# Generated by Django 4.1.1 on 2022-09-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_fileinfolder_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfolder',
            name='title',
        ),
    ]
