# Generated by Django 4.1.2 on 2022-10-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_filefolder_description_alter_fileinfolder_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
