# Generated by Django 4.1.9 on 2023-06-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_planned'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Youtube video ID'),
        ),
    ]
