# Generated by Django 4.1.9 on 2023-07-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_alter_project_is_public_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilesToFolder',
        ),
    ]
