# Generated by Django 4.1.9 on 2023-09-03 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('project', '0019_project_production_project_project_site_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filefolder',
            options={'verbose_name': 'Папка проекту', 'verbose_name_plural': 'Папки проекту'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографії'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['date'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекти'},
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип проекту'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='article_date',
            field=models.DateField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Початок'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False, help_text='якщо увімкнуто - бачать усі відвідувачі'),
        ),
        migrations.AlterField(
            model_name='project',
            name='production',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Виробництво'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_site_link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на сторінку проекту'),
        ),
        migrations.AlterField(
            model_name='project',
            name='representative_image',
            field=models.ForeignKey(blank=True, help_text='малюнок заголовку проекту', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='running_time_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Тривалість'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
