# Generated by Django 4.1.9 on 2023-09-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_alter_filefolder_options_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='top_priority',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
